tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Improved top (interactive process viewer)
brew "htop"
# Mac App Store command-line interface
brew "mas"
# Tools for one-time password authentication systems
brew "oath-toolkit"
# Manage compile and link flags for libraries
brew "pkg-config"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Text interface for Git repositories
brew "tig"
# Simplified and community-driven man pages
brew "tldr"
# Program that allows you to count code, quickly
brew "tokei"
# Vi 'workalike' with many additional features
brew "vim"
# Show the current WiFi network password
brew "wifi-password"
# General-purpose lossless data-compression library
brew "zlib"
# App to build and share containerized applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Web browser
cask "google-chrome"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Control your tools with a few keystrokes
cask "raycast"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Keys Multiplatform", id: 1494642810
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
